import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TopBar from "@/components/TopBar";

export const clashDisplay = localFont({
    src: "./fonts/ClashDisplay-Variable.woff2",
    display: "swap",
    variable: "--font-clash-display",
});

const raleway = Raleway({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    style: "normal",
    subsets: ["latin"],
    variable: "--font-releway",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${clashDisplay.variable} ${raleway.variable} font-clashDisplay antialiased`}
            >
                <TopBar />
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
